### ISSUE TITLE
Multiple processes per host support in Monit

### ISSUE THREAD

**Issue by okoriko** [seuros/capistrano-sidekiq#103]
@seuros 
Seems like one of the latests commit:
https://github.com/seuros/capistrano-sidekiq/commit/574588861839a80920e681e0e9d9c52311bf8875

Reverted changes to support different processes count per each host. It was added in:
https://github.com/seuros/capistrano-sidekiq/commit/dcab28bef45f3885d74c89faeeaa075e42fa39ed

Was this intentional?

**Comment by vnazarenko** [comment]
+1 different process count is not working now (

**Comment by andresakata** [comment]
I just had the same problem here. Shouldn't monit tasks support a different number of processes per role?
