### ISSUE TITLE
sidekiq:quiet fails on initial deployment

### ISSUE THREAD

**Issue by cmckni3** [seuros/capistrano-sidekiq#108]
I am using Capistrano 2.15.6 with capistrano-sidekiq 0.5.3.

`sidekiq:quiet` fails to run during initial deployment because `bundle:install` has not run yet so I receive the error message `bundler: sidekiqctl not found`. I tried using `deploy:cold` but it fails as well.

Bundler's integration with Capistrano runs `bundle:install` before `deploy:finalize_update` as seen [here](https://github.com/bundler/bundler/blob/master/lib/bundler/capistrano.rb#L13). I might switch to Capistrano 3 and `capistrano-bundler` at some point but not at this time.

Any suggestions?

**Comment by seuros** [comment]
There is nothing much we can do without heavy hacks. Capistrano 3 did fix this issue.

**Comment by cmckni3** [comment]
Fair enough. I'll consider upgrade to Capistrano 3.

Closing
