### ISSUE TITLE
rvm1 issue

### ISSUE THREAD

**Issue by dziulius** [seuros/capistrano-sidekiq#110]
I don't have much experience with capistrano stuff, but I've came up with issue that when running stop command, it does not use rvm-auto command.

After some digging I've found that [rvm_map_bins](https://github.com/seuros/capistrano-sidekiq/blob/master/lib/capistrano/tasks/sidekiq.rake#L15) are being set, while rvm1-capistrano3 uses [rvm1_map_bins](https://github.com/rvm/rvm1-capistrano3/blob/master/lib/rvm1/tasks/capistrano3.rake#L16). If this gem is not supposed to be used with rvm1-capistarno3, then please ignore this issue.

**Comment by seuros** [comment]
https://github.com/capistrano/rvm is the official rvm capistano gem.

**Comment by dziulius** [comment]
I'm sysadmin an project I'm working on is setup to use [rvm1-capistrano3](https://github.com/rvm/rvm1-capistrano3).

So I'll just use local fix:
```ruby
set :rvm1_map_bins, fetch(:rvm1_map_bins, []).push('sidekiq', 'sidekiqctl')
```

Thanks, anyway!
