### ISSUE TITLE
rvm1-capistrano3 support

### ISSUE THREAD

**Issue by sauliusgrigaitis** [seuros/capistrano-sidekiq#111]
Capistrano-sidekiq doesn't support rvm1-capistrano3 ( #110 ). Currently there are two RVM support gems for Capistrano:

1) https://github.com/capistrano/rvm/ - maintained by Capistrano developers. Unfortunately not really usable, it works only in some specific cases.

2) https://github.com/rvm/rvm1-capistrano3 - defacto RVM support for Capistrano that works just great. Maintainers is @mpapis - RVM author.

@mpapis tried to merge https://github.com/rvm/rvm1-capistrano3 into https://github.com/rvm/rvm1-capistrano3 - unfortunately it was rejected by Capistrano developers https://github.com/capistrano/rvm/pull/34 .

There should be support either for both of these gems or at least for defacto RVM support gem https://github.com/rvm/rvm1-capistrano3 .

**Comment by mpapis** [comment]
@sauliusgrigaitis try:
```ruby
set :rvm1_map_bins, fetch(:rvm1_map_bins).to_a.concat(%w(sidekiq sidekiqctl))
```
and then you could add it here: https://github.com/seuros/capistrano-sidekiq/blob/master/lib/capistrano/tasks/sidekiq.rake#L15

**Comment by sauliusgrigaitis** [comment]
Thanks @mpapis, that's what we have in config/deploy.rb, because we know it. Those who don't know this - waste their time.

**Comment by mpapis** [comment]
oh, then could you open a PR with the fix, it's so trivial I do not think @seuros would be against it :)

**Comment by sauliusgrigaitis** [comment]
@mpapis please check above :)

**Comment by seuros** [comment]
I opened a PR few days ago to fix the issue : https://github.com/rvm/rvm1-capistrano3/pull/64 . 
There is multiple gems that support only capistrano/rvm gem.

**Comment by sauliusgrigaitis** [comment]
Deadlock.

**Comment by mpapis** [comment]
`rvm1-capistrano3` `1.4.0` released to add support for `rvm_map_bins`

**Comment by sauliusgrigaitis** [comment]
:+1:

**Comment by mpapis** [comment]
I guess we can close this one

**Comment by sauliusgrigaitis** [comment]
Sure, thanks @mpapis !
