### ISSUE TITLE
Atomic operation?

### ISSUE THREAD

**Issue by chengguangnan** [seuros/capistrano-sidekiq#112]
I noticed a problem which the Sidekiq received a USR1 and went down for days. 

I don't recall exactly. It seems that I was making a new deployment halted the deployment-in-progress. Without noticing that the Sidekiq has been shutdown.

It actually happened once few months ago. If there is an way to make this restart atomic?

**Comment by seuros** [comment]
You can have inspeqtor monitor your process, if sidekiq is down for more than X minutes, you will receive an email .
