### ISSUE TITLE
Upstart

### ISSUE THREAD

**Issue by sahin** [seuros/capistrano-sidekiq#114]
@seuros , I just saw that we made 5000 deployment with capistrano-sidekiq, we have very fast deployment and we deploy new code changes very quickly in our background process servers. 

I like capistrano-sidekiq a lot, it is just a huge time saver. and one of coolest thing that capistrano-sidekiq allows us to do is that we able to make single purpose sidekiq projects. so we divided our 1 big sidekiq repo into 14.

I would love to start a discussion, to improve the flow. 

now it is like

unmonitor
kill
deploy
monit

is there any way use utilize capistrano folder structure and do zero time restart?

**Comment by seuros** [comment]
Thank you !
We can work on a solution together if you want.
I'm currently working with @lpaulmp on a feature to have multiple processes support. It will be good to have zero time restart.

**Comment by sahin** [comment]
zero-time restarts will be great. is there any branch that u guys working on. 

It can be also a good idea to print monit status `app_name` at the end of deployment

**Comment by w1mvy** [comment]
multiple processes support and zero time restart is very nice! https://github.com/lpaulmp/capistrano-sidekiq/commits/v1
When do you release this feature?

**Comment by seuros** [comment]
This week.

**Comment by seuros** [comment]
@w1mvy we tried to work on the zero time deployment, but we dropped this idea for good. 
I don't think it possible to implement this feature for the simple reason that sometime there is migrations that need to be run, what will happen if workers are still spinned while the schema of the database is being changed ?

**Comment by w1mvy** [comment]
@seuros 

thanks for your reply.

> we dropped this idea 

I see.
I think, when schema of the database changed and if want to zero down time restart, there is need feature of sidekiq like `USR2` signal of unicorn. I feel difficult likely.

So, how about multi config support？ Your changes contain multi support, and there is demand for this featue. like these PR #120 #81.
