### ISSUE TITLE
sidekiq_user option ignored

### ISSUE THREAD

**Issue by jhollinger** [seuros/capistrano-sidekiq#121]
The `:sidekiq_user` option doesn't do anything - I can't even find a reference to it in the code. Am I missing something?

**Comment by seuros** [comment]
https://github.com/seuros/capistrano-sidekiq/blob/master/lib/capistrano/tasks/sidekiq.rake#L219

It used to run sidekiq under another user than the one we ssh with.

**Comment by jhollinger** [comment]
I assumed. `capistrano3-puma` has the same option, which I find very useful. Why was it removed form this gem?

**Comment by jhollinger** [comment]
Oh, I see. Looks like it was recently added to master? I'm running `0.5.3` which just doesn't have it yet. So if I switch to running out of master, I can count on this feature remaining?

**Comment by seuros** [comment]
i will release now 0.5.4 for you.

**Comment by seuros** [comment]
Done.

**Comment by jhollinger** [comment]
Thanks for the fast response. Works for `sidekiq:start` task, but it doesn't seem to work for `sidekiq:monit:config`.

**Comment by seuros** [comment]
can you fix it and open a PR ?

**Comment by jhollinger** [comment]
Sure thing
