### ISSUE TITLE
Error sidkiq when deploy

### ISSUE THREAD

**Issue by BorisBresciani** [seuros/capistrano-sidekiq#123]
Hey, i have this error when I deploy my app with capistrano

sidekiq stdout: Nothing written
sidekiq stderr: No such file or directory @ rb_sysopen - /home/deploy/apps/flat-icons/shared/log/sidekiq.log

I don't understand why this error appears, thank you for your future help

Regards,
Boris

**Comment by seuros** [comment]
In your deploy.rb, add something like
```ruby
set :linked_dirs, %w(log tmp/pids)
````

**Comment by mdesantis** [comment]
What if tmp is already included in linked_dirs? I get the error Too many levels of symbolic links now
