### ISSUE TITLE
Should not override options from --config file, if specified as a command line option

### ISSUE THREAD

**Issue by heaven** [seuros/capistrano-sidekiq#129]
I have set :sidekiq_options_per_process, ["--config config/sidekiq-common.yml"] but the logfile option is being overridden during deploy:

```
INFO [c865bcfa] Running /usr/local/rvm/bin/rvm ruby-2.1.2-patch do bundle exec sidekiq --index 0 --pidfile /var/www/.../shared/tmp/pids/sidekiq-0.pid --environment staging --logfile /var/www/.../shared/log/sidekiq.log --config config/sidekiq-common.yml --daemon
```

**Comment by ypadlyak** [comment]
@seuros ?
Also monit config is generated without taking into account :sidekiq_options_per_process

**Comment by ypadlyak** [comment]
My guess is that you are overriding Monit template, which is not taking into account sidekiq_options_per_process
