### ISSUE TITLE
pidfile being appended with -0

### ISSUE THREAD

**Issue by damienh** [seuros/capistrano-sidekiq#134]
We are using upstart to start our sidekiq process which uses our `sidekiq.yml` (see below) on startup of the server, however when we do a deployment I can see that capistrano-sidekiq is starting a sidekiq process with these options `bundle exec sidekiq --index 0 --pidfile /var/www/staging.codeclub.org.uk/shared/tmp/pids/sidekiq-0.pid --environment staging --logfile /var/www/staging.codeclub.org.uk/shared/log/sidekiq.log --config /var/www/current/config/sidekiq.yml --concurrency 4 --daemon`

To me this looks like capistrano-sidekiq is ignoring my pidfile declaration. I also have it set inside `deploy.rb` see below. Anyone got any ideas to why it wont use `sidekiq.pid` as the pidfile. 

`sidekiq.yml`

```
:verbose: true
:pidfile: ./tmp/pids/sidekiq.pid

:timeout: 60

development:
  :concurrency: 4
sandbox:
  :concurrency: 4
staging:
  :concurrency: 4
production:
  :concurrency: 4
```

`deploy.rb`

```
set :sidekiq_default_hooks, false
set :sidekiq_pid,           File.join("#{current_path}", 'tmp', 'pids', 'sidekiq.pid')
set :sidekiq_config,        "#{current_path}/config/sidekiq.yml"
```

**Comment by bogdanRada** [comment]
+1. Have same issue

**Comment by bogdanRada** [comment]
I actually had to make this make this hack in my config/deploy.rb file in order to work properly:

```ruby
def processes_pids
    pids = []
    sidekiq_roles = Array(fetch(:sidekiq_role))
    sidekiq_roles.each do |role|
      next unless host.roles.include?(role)
      processes = fetch(:"#{ role }_processes") || fetch(:sidekiq_processes)
      processes.times do |idx|
        post_fix = idx > 0 ? "-#{idx}" : ''
        pids.push fetch(:sidekiq_pid).gsub(/\.pid$/, "#{post_fix}.pid")
      end
    end

    pids
  end
```
Maybe there is a easier fix?

**Comment by damienh** [comment]
@bogdanRada can I see your deploy.rb file. I cant get your fix to work.

**Comment by metavida** [comment]
Seems like this behavior (where "-0" is added to pidfiles) was intentionally added in #116 to fix #44

**Comment by ljachymczyk** [comment]
Is there any way to prevent appending '-0' to pidfile?

**Comment by metavida** [comment]
@ljachymczyk yes! You can use v0.5.3 of this gem (the append -0 behavior was [introduced in v0.5.4](https://github.com/seuros/capistrano-sidekiq/compare/v0.5.3...v0.5.4#diff-22e72e49e022ca1b14706f04c8df5919L34) or you can try using [my company's fork of this gem](https://github.com/haikulearning/capistrano-sidekiq) which allows you to specify the pidfile name in your sidekiq.yml config file.

**Comment by ljachymczyk** [comment]
@metavida that's exactly what I did. But anyway, I should be able to do this also with the most up-to-date gem version somehow.
