### ISSUE TITLE
help:  Invalid pidfile content

### ISSUE THREAD

**Issue by syllogismus** [seuros/capistrano-sidekiq#137]
hi, i am deploying ror4 with capistrano, but this fails:

usr/local/rvm/bin/rvm 2.1.0 do sidekiqctl stop /apps/app_a/production/shared/tmp/pids/sidekiq-0.pid 10 as administrator@domain.com
DEBUG [2f0b00a1] Command: cd /apps/app_a/production/releases/20151223140143 && ( RVM_BIN_PATH=~/.rvm/bin /usr/local/rvm/bin/rvm 2.1.0 do sidekiqctl stop /apps/app_a/production/shared/tmp/pids/sidekiq-0.pid 10 )
DEBUG [2f0b00a1]        Invalid pidfile content

it works locally, need help

thx

**Comment by seuros** [comment]
can you give me the output of 
```
cat apps/app_a/production/shared/tmp/pids/sidekiq-0.pid

**Comment by syllogismus** [comment]
its empty - nothing there - i really appreciate your help!!!

**Comment by seuros** [comment]
That the issue then, the file should contain the pid of the process (an integer). 

delete that file manually and try to start process with capistrano, then check if there is the pid in the file.

**Comment by syllogismus** [comment]
whooha - it works now, i got a file with pid#

thank you soo much!!

**Comment by seuros** [comment]
Welcome, and happy holidays.

**Comment by syllogismus** [comment]
do you know why this happens?
 Running ~/.rvm/bin/rvm default do sidekiq --index 0 --pidfile /apps/
domain.com/domain.com/production/shared/tmp/pids/sidekiq-0.pid
--environment production --logfile /apps/
domain.com/domain.com/production/shared/log/sidekiq.log --daemon as
administrator@domain.com
DEBUG [b70fc839] Command: cd /apps/domain.com/domain.com/production/current
&& ~/.rvm/bin/rvm default do sidekiq --index 0 --pidfile /apps/
domain.com/domain.com/production/shared/tmp/pids/sidekiq-0.pid
--environment production --logfile /apps/
domain.com/domain.com/production/shared/log/sidekiq.log --daemon
DEBUG [b70fc839]
DEBUG [b70fc839]
DEBUG [b70fc839]        RVM is not a function, selecting rubies with 'rvm
use ...' will not work.
DEBUG [b70fc839]
DEBUG [b70fc839]
DEBUG [b70fc839]
DEBUG [b70fc839]        You need to change your terminal emulator
preferences to allow login shell.
DEBUG [b70fc839]
DEBUG [b70fc839]        Sometimes it is required to use `/bin/bash --login`
as the command.
DEBUG [b70fc839]
DEBUG [b70fc839]        Please visit
https://rvm.io/integration/gnome-terminal/ for an example.
DEBUG [b70fc839]
DEBUG [b70fc839]
DEBUG [b70fc839]
DEBUG [b70fc839]        /home/administrator/.rvm/scripts/set: line 19:
exec: sidekiq: not found
DEBUG [b70fc839]
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as
administrator@domain.com: sidekiq exit status: 127
sidekiq stdout:
RVM is not a function, selecting rubies with 'rvm use ...' will not work.

You need to change your terminal emulator preferences to allow login shell

On Wed, Dec 23, 2015 at 9:43 AM, Abdelkader Boudih <notifications@github.com
