### ISSUE TITLE
capistrano-sidekiq ignores upstart job

### ISSUE THREAD

**Issue by Genda1ph** [seuros/capistrano-sidekiq#142]
Hello, I've encountered an issue with capistrano-sidekiq (0.5.3) and upstart (1.12.1).
Developer asked me to install upstart config provided on sidekiq's wiki to run it as an upstart job on our staging and production servers (https://github.com/mperham/sidekiq/wiki/Deploying-to-Ubuntu).
However during deploy something strange started to happen:
1. sidekiq entered stopping state then its process died
2. another sidekiq process started in a couple of seconds (ok, we expect this...)
3. and then second process started in another couple of seconds
After some googling I figured that capistrano-sidekiq looks for sidekiq, sends SIGUSR1 and then SIGTERM. Upstart detects that sidekiq died and respawns it. After deployment is finished, capistrano starts second sidekiq process, overwriting pidfile.

If I tell upstart to ignore sidekiq exiting on SIGTERM with code 0 (`normal exit 0 TERM`), it just takes sidekiq from upstart's monitoring, this is merely a workaround.

So, there are three possible fixes:
- Check for existence of pidfile and process upon post-deploy and then kill sidekiq again
- Utilize upstart
- Come up with workarounds in upstart config
- Use some kind of ruby watcher for sidekiq

I think the best solution would be integrating with upstart, or documenting some other way of monitoring sidekiq compatible with capistrano-sidekiq.

**Comment by simonasdev** [comment]
Would really like this feature
