### ISSUE TITLE
capistrano-sidekiq is broken with capistrano-rbenv

### ISSUE THREAD

**Issue by Kukunin** [seuros/capistrano-sidekiq#147]
I've figured out, that this commit breaks sidekiq capistrano task: https://github.com/seuros/capistrano-sidekiq/commit/8a49d7608e08a61a6f9d652225014565caecd982.

I get this command running:

```
DEBUG [c94fd95b] Finished in 0.397 seconds with exit status 0 (successful).
INFO [eb270192] Running bundle exec sidekiqctl stop /var/www/matic-home/shared/tmp/pids/sidekiq.pid 10 as deploy@m-staging-01.matichome.com
DEBUG [eb270192] Command: cd /var/www/matic-home/current && ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.1.5" ; bundle exec sidekiqctl stop /var/www/matic-home/shared/tmp/pids/sidekiq.pid 10 )
```

Instead, I expect this command to run

```
INFO [69501030] Running RBENV_ROOT=$HOME/.rbenv RBENV_VERSION=2.1.5 $HOME/.rbenv/bin/rbenv exec bundle exec sidekiq --index 0 --pidfile /var/www/matic-home/shared/tmp/pids/sidekiq.pid --environment production --logfile /var/www/matic-home/shared/log/sidekiq.log -q default -q mailers -q sync -c 3 --daemon as deploy@m-staging-01.matichome.com
DEBUG [69501030] Command: cd /var/www/matic-home/current && ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.1.5" ; RBENV_ROOT=$HOME/.rbenv RBENV_VERSION=2.1.5 $HOME/.rbenv/bin/rbenv exec bundle exec sidekiq --index 0 --pidfile /var/www/matic-home/shared/tmp/pids/sidekiq.pid --environment production --logfile /var/www/matic-home/shared/log/sidekiq.log -q default -q mailers -q sync -c 3 --daemon )
INFO [69501030] Finished in 1.199 seconds with exit status 0 (successful).
```

**Comment by seuros** [comment]
You are using bundler, you should add capistrano-bundler to your gem files.

**Comment by stefanosc** [comment]
same issue here, reverting to 0.5.3 prevents it.

**Comment by stefanosc** [comment]
@Kukunin did you find a way to get the latest release to work?

**Comment by stefanosc** [comment]
@Kukunin @seuros  could you share anything?
Thank you!

**Comment by guillehorno** [comment]
Hi,
I faced the same issue and diggind around the capistrano-sidekiq code found this setting that made the `bundle exec` work correctly (with the env variables of rbenv). You just need to add this into the deploy.rb file

`set :rbenv_map_bins, fetch(:rbenv_map_bins).to_a.concat(%w(sidekiq sidekiqctl))`

Hope it helps.

**Comment by Paprikas** [comment]
I have just added to default rbenv_map_bins
`set :rbenv_map_bins, %w(rake gem bundle ruby rails sidekiq sidekiqctl)`

**Comment by lbraun** [comment]
We are using rvm so I had to add:
```
set :rvm_map_bins, %w(rake gem bundle ruby rails sidekiq sidekiqctl)
```
Using concatenation did not work. Can anyone explain why this is necessary? Does this capistrano-sidekiq delete the default rvm_map_bins somehow?

**Comment by jkarnesPerfectCube** [comment]
It does not delete them, but it does set them based on what currently exists: `set :rvm_map_bins, fetch(:rvm_map_bins).to_a.concat(%w(sidekiq sidekiqctl))`
