### ISSUE TITLE
Reducing sidekiq_processes in Capistrano file does not kill existing processes

### ISSUE THREAD

**Issue by salgo** [seuros/capistrano-sidekiq#151]
We had 2 processes and we reduced the sidekiq_processes 1 in the Capistrano config/deploy/env.rb file and although the monitrc configuration was updated correctly, we saw the following problems: 
1. the other process wasn't `sidekiqctl quiet` and then killed
2. it wasn't `monit unmonitor`
3. it wasn't killed either.

This is leading me to believe such a change is simply not supported as it doesn't seem to be handled at all? Or, of course it might be my setup? Any pointers much appreciated.

**Comment by seuros** [comment]
@salgo you are right. This change is not supported .
As workaround: 
* Quiet all processes.
* Unmonitor them
* Stop them when they finish.
* change your configuration to 1
* regenerate the monite configuration and start sidekiq.

**Comment by nextofsearch** [comment]
@seuros 
Hi, 
I had the same issue. So I specified 'set :sidekiq_processes, 1' in staging.rb and production.rb but the setting does not work. It only works when I put it in deploy.rb. I thought that settings in stage-specific files will override the ones in deploy.rb. Am I misunderstood here?
