### ISSUE TITLE
monit template error

### ISSUE THREAD

**Issue by brahmadpk** [seuros/capistrano-sidekiq#152]
Hi,

When using the included monit template, the following error is thrown:

```
Tasks: TOP => sidekiq:monit:config
(See full trace by running task with --trace)
The deploy has failed with an error: undefined method `sidekiq_user' for #<SSHKit::Backend::Netssh:0x007fb82acc9888>
Did you mean?  sidekiq_queues
```

The same error also appears for sidekiq_require

Without the template, it works well.

Am I missing something that needs to be defined in deploy.rb? Thanks in advance for help.

**Comment by nextofsearch** [comment]
Hi,

I am having the same problem but only in staging, not in production. The settings are virtually the same in both. I am lost here.

**Comment by nextofsearch** [comment]
Here's the more detailed error:

`cap staging sidekiq:monit:config --trace
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke rvm:hook (first_time)
** Execute rvm:hook
** Invoke rvm:check (first_time)
** Execute rvm:check
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
ruby-2.3.1@rails42
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke sidekiq:monit:config (first_time)
** Execute sidekiq:monit:config
cap aborted!
NoMethodError: undefined method `sidekiq_user' for #<SSHKit::Backend::Netssh:0x007fdb620765a8>
Did you mean?  sidekiq_queues
(erb):5:in `block in upload_sidekiq_template'
(erb):2:in `each'
(erb):2:in `each_with_index'
(erb):2:in `upload_sidekiq_template'
/Users/danolee/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/erb.rb:864:in `eval'
/Users/danolee/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/erb.rb:864:in `result'
/Users/danolee/.rvm/gems/ruby-2.3.1@rails42/gems/capistrano-sidekiq-0.5.4/lib/capistrano/tasks/sidekiq.rake:231:in `upload_sidekiq_template'
/Users/danolee/.rvm/gems/ruby-2.3.1@rails42/gems/capistrano-sidekiq-0.5.4/lib/capistrano/tasks/monit.rake:31:in `block (4 levels) in <top (required)>'
/Users/danolee/.rvm/gems/ruby-2.3.1@rails42/gems/sshkit-1.11.1/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/danolee/.rvm/gems/ruby-2.3.1@rails42/gems/sshkit-1.11.1/lib/sshkit/backends/abstract.rb:29:in `run'
/Users/danolee/.rvm/gems/ruby-2.3.1@rails42/gems/sshkit-1.11.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => sidekiq:monit:config`

**Comment by nextofsearch** [comment]
Hi, I solved it.

You need to specify the repository of the gem as below. I don't understand why this makes a difference.
-  gem 'capistrano-sidekiq'
+  gem 'capistrano-sidekiq', github: 'seuros/capistrano-sidekiq'
