### ISSUE TITLE
Sidekiq never processes queue

### ISSUE THREAD

**Issue by abrambailey** [seuros/capistrano-sidekiq#154]
Using capistrano 3.4.0 I have the following in my deploy.rb for sidekiq
```ruby
set :sidekiq_default_hooks, true
set :sidekiq_role, :app  
set :sidekiq_config, -> { File.join(current_path, 'config', 'sidekiq.yml') } 
set :sidekiq_env, ['production', 'qa']  
set :sidekiq_options, "-q default -q mailers"
set :pty, false
```
Then in my sidekiq.yml
```yml
:verbose: true
:concurrency: 25
:queues:
  - [mailers, 7]
  - [default, 5]
```
When deploying I see:
```
bundle exec sidekiq --index 0 --pidfile /webapps/myproject/qa/shared/tmp/pids/sidekiq-0.pid --environment ["production", "qa"] --logfile /webapps/myproject/qa/shared/log/sidekiq.log --config /webapps/myproject/qa/current/config/sidekiq.yml -q default -q mailers --daemon
```
When viewing the sidekiq admin I see:

![image](https://cloud.githubusercontent.com/assets/978462/16205117/eac90f4a-36e7-11e6-9c5d-4f4bb3010064.png)

**Comment by seuros** [comment]
`set :sidekiq_env, ['production', 'qa']`   is wrong. set it to either qa or production.

**Comment by abrambailey** [comment]
I removed that line completely and it began working, just before you typed this. So how would I enable on both environments? Just leave it blank?

**Comment by seuros** [comment]
you set it in both `deploy/qa.rb` and `deploy/production.rb` to it respective value.

**Comment by abrambailey** [comment]
Oh I see. Sorry, sort of a n00b with capistrano. Thanks.

**Comment by seuros** [comment]
No problem. 👍

**Comment by zackperdue** [comment]
Did you ever get your queued jobs to process?
