### ISSUE TITLE
Separate config per role

### ISSUE THREAD

**Issue by kalinchuk** [seuros/capistrano-sidekiq#161]
It would be nice to set separate config files per role. For example, `role_1` should only process the `low_priority` queue and `role_2` should only process the `high_priority` queue. That could be configured in a `config.yml` file per role or something.

**Comment by kalinchuk** [comment]
Right now I run a task before sidekiq restarts to copy over the correct config file to `sidekiq.yml` depending on the role.

**Comment by vnazarenko** [comment]
Also #117 could help.

**Comment by LucasPiffer** [comment]
Hey guys, having a hard time to figure out how to run a different config file with capistrano-sidekiq. First I thought the following code would make sense:

```
set :init_system, :systemd
set :sidekiq_processes, 2
set :sidekiq_roles, [:worker]
set :sidekiq_options_per_process, [
  "--logfile log/sidekiq_web-1.log --config config/sidekiq.yml",
  "--logfile log/sidekiq_web-2.log --config config/sidekiq_web.yml"
]
```

But did not work at all. Do you know if is it possible to have different config files per different processes? Sorry for asking I'm used to use Docker but now I'm trying to help a friend which uses capistrano-sidekiq and also is having a hard time with the doc.
