### ISSUE TITLE
New signals in Sidekiq 5.0 

### ISSUE THREAD

**Issue by ivanovaleksey** [seuros/capistrano-sidekiq#172]
Hi @seuros,

according to [release notes](https://github.com/mperham/sidekiq/blob/master/5.0-Upgrade.md)
> Sidekiq's quiet signal is now TSTP (think of it as Thread SToP) instead of USR1 as USR1 is not available on JRuby. USR1 will continue to be supported in Sidekiq 5.x for backwards compatibility and will be removed in Sidekiq 6.x

It seems like we can update signals, bump required Sidekiq version in gemspec, and update major version of the capistrano-sidekiq.

What do you think?

**Comment by seuros** [comment]
Done. Thank you.
