### ISSUE TITLE
Ignoring 'roles' config

### ISSUE THREAD

**Issue by lloydwatkin** [seuros/capistrano-sidekiq#200]
Hi, seems to be linked to seuros/capistrano-sidekiq#191, I've upgraded to 1.0.2 and sidekiq is coming up on all my hosts on deploy (not just the specified role). Other config is being set so its not a case of the config file being read.

Here's my `config/sidekiq.yml`:

```yml
:queues:
  - [notifications,20]
  - [high_priority,10]
  - [<%= `hostname`.strip %>,5]
  - [default,2]
  - mailers
  - low_priority
:concurrency: 15
:roles: :admin
```

...and I can confirm that downgrading to 0.20.0 works as expected.

**Comment by falm** [comment]
In v1.0 you should change config/deploy.rb (or config/deploy/production.rb) with the following
```ruby
set :sidekiq_roles, :admin
```
