### ISSUE TITLE
Consider adding MALLOC_ARENA_MAX to systemd template

### ISSUE THREAD

**Issue by aganov** [seuros/capistrano-sidekiq#216]
Can you consider adding `Environment=MALLOC_ARENA_MAX=2` to the systemd template (and maybe to the upstart template too). There have been discussion about long-lived ruby applications like `sidekiq` that will benefit from lower glibc `M_ARENA_MAX`. You can find more information here:

https://www.mikeperham.com/2018/04/25/taming-rails-memory-bloat/
https://bugs.ruby-lang.org/issues/14718
https://bugs.ruby-lang.org/issues/14759

https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service#L36-L38

**Comment by seuros** [comment]
You can use `sidekiq_service_unit_env_vars`  to set it.
