### ISSUE TITLE
Systemd and deploys

### ISSUE THREAD

**Issue by Systho** [seuros/capistrano-sidekiq#219]
I think systemd script should not be configured to restart sidekiq because it would add a new sidekiq process at each deployment.

Deployment process is :
 1: quiet sidekiq
 2: deploy
 3: stop sidekiq
 4: start a new sidekiq

After step 3, systemd would notice the death of the process and start a new one. But the deploy would start a new process, too. 

I think the systemd script should just start sidekiq on boot and then forget about it.

**Comment by chenjenping** [comment]
I think the `stop task` has already handled this, it tells systemd to stop the process?
```ruby
when :systemd
  execute :systemctl, "--user", "stop", fetch(:service_unit_name)
```

**Comment by Systho** [comment]
Oh My bad, I was using an old version of capistrano sidekiq.
