### ISSUE TITLE
Sidekiq not starting

### ISSUE THREAD

**Issue by tomprats** [seuros/capistrano-sidekiq#220]
I've tried various setups but I can't seem to get sidekiq to start. I run `cap production sidekiq:install` with the following:

```
set :init_system, :systemd
set :pty, false
set :service_unit_name, "sidekiq_#{fetch(:application)}_#{fetch(:stage)}.service"
set :sidekiq_config, -> { File.join(shared_path, "config", "sidekiq.yml") }
set :sidekiq_log, -> { File.join(shared_path, "log", "sidekiq.log") }
```

It looks like it creates the service fine, but for some reason it is erroring:

> systemctl --user status sidekiq_tomify_production.service
> ● sidekiq_tomify_production.service - sidekiq for tomify (production)
>    Loaded: loaded (/home/deploy/.config/systemd/user/sidekiq_tomify_production.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Wed 2018-10-24 06:21:21 UTC; 49s ago
>  Main PID: 15713 (code=exited, status=203/EXEC)

I'm not sure why it'd be failing like that. I tried mapping the sidekiq commands with bundle exec but I had no luck. I'm not sure what else to try at this point

**Comment by chenjenping** [comment]
Maybe you can execute the command behind `ExecStart` in sidekiq_tomify_production.service file manually, then it will show you more specific error.

**Comment by Paprikas** [comment]
If you use rbenv, you can check my manual https://gist.github.com/Paprikas/11fc850f81b687d9cbb7a8efb5ead208

**Comment by tomprats** [comment]
I ended up not being able to find the specific cause but fixed it eventually after rebuilding the box and playing around with some more things
