### ISSUE TITLE
Using systemd, run sidekiq as a system service rather than "user service"

### ISSUE THREAD

**Issue by sonxurxo** [seuros/capistrano-sidekiq#228]
Hi all

Currently this gem invokes `systemctl` hardcoding the `--user` option, like this:

```ruby
execute :systemctl, '--user', 'start', fetch(:service_unit_name)
```

This prevents users from running Sidekiq as a _system service_ rather than as a _user service_. It would be great if one could specify this with a configuration option. Something like:

```ruby
set :init_system_type, :system   # or ':user'
```

What do you think? I could work on a PR for this if you consider it.

--- 

**A bit of context of why I think this could be a good idea:**

We're currently deploying a Rails app with Capistrano. We have two roles: a web server role and a worker role; only the latter will run Sidekiq, along with other services. Instances of both roles run in two different AWS Autoscaling Groups respectively. Autoscaling the worker is a little tricky, because we want it to boot and launch Sidekiq and the other services immediately.

If we configure the services as "`--user`" services, these will only be started when a user starts a session in the machine; but we need the services to start up automatically just after the machine boots.

**Comment by TeamNautilus** [comment]
We worked around the issue by enabling lingering for the "deployer" user.
```
# loginctl enable-linger username
```
But maybe there is a better solution.
If you follow the system scope, however, you need to give privilege to the user to reload the service, so it will complicate a bit the process.

**Comment by sonxurxo** [comment]
Yep, our deployer is currently a sudoer so we ended up using system services, but yours is an interesting workaround, I didn't even know about that feature 👍 . We'll give it a try.

**Comment by megane42** [comment]
+1 too, because Amazon Linux 2 (or RHEL7) does not support `--user` option.
https://bugzilla.redhat.com/show_bug.cgi?id=1173278

**Comment by jnimety** [comment]
I would like this functionality as well. Managing user services is frowned upon with Puppet (and difficult to implement). Giving the deploy user access via sudoers is straight forward:

```
capistrano ALL= NOPASSWD: /usr/bin/systemctl reload sidekiq
capistrano ALL= NOPASSWD: /usr/bin/systemctl restart sidekiq
capistrano ALL= NOPASSWD: /usr/bin/systemctl start sidekiq
capistrano ALL= NOPASSWD: /usr/bin/systemctl status sidekiq
capistrano ALL= NOPASSWD: /usr/bin/systemctl stop sidekiq
```

**Comment by andrecgro** [comment]
Maybe I'm missing something here but, how can I make this gem work on amazon RHEL7 ?
I'm receiving the `systemctl stderr: Failed to get D-Bus connection: No such file or directory` message everytime I try to deploy after adding the capistrano-sidekiq gem.

**Comment by seuros** [comment]
@andrecgro , i using amazon RHEL7 and it working. Are you up to date ?

**Comment by andrecgro** [comment]
Yes, I would say so.

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
```
$ uname -r
3.10.0-1160.15.2.el7.x86_64
```

To use the gem, should I do anything else than just adding it to my Capfile?
```
...
require 'capistrano/sidekiq'
install_plugin Capistrano::Sidekiq  # Default sidekiq tasks
# Then select your service manager
install_plugin Capistrano::Sidekiq::Systemd 
...
```
