### ISSUE TITLE
`systemd --user` doesn't work on CentOS7

### ISSUE THREAD

**Issue by grezar** [seuros/capistrano-sidekiq#237]
Hi there.
I tried to integrate this gem into my Capistrano to deploy Sidekiq on CentOS7.
But, but but but, Systemd included in CentOS7 doesn't support Systemd-user so `systemd --user` which is used to control Sidekiq process in some tasks doesn't work on my environment.

```
$ systemctl --user
Failed to get D-Bus connection: No such file or directory
```

Nobody was in trouble with the same thing?

**Comment by grezar** [comment]
I found the almost same issue #228 so I close this.

**Comment by maxingjia1314** [comment]
Hello, I'd like to ask how you handled it. I haven't found out what their solution is
