### ISSUE TITLE
NameError: uninitialized constant Capistrano::Sidekiq in latest beta

### ISSUE THREAD

**Issue by guillehorno** [seuros/capistrano-sidekiq#242]
Hi,

I was trying the gem against master, and I get the following error:
```
cap aborted!
NameError: uninitialized constant Capistrano::Sidekiq
/Users/guille/Desarrollo/proyectos/Safiro-Jobs/Codename-SocialHunt/Capfile:32:in `<top (required)>'
```

I've tried debugging but can't seem to find out why it's not loading the Sidekiq plugin. Happy to help and send a PR if you could point me in the right direction, what should I try?

Thanks!

**Comment by gh-assetplan** [comment]
Sorry, I'm not sure what happened, now its working :)

**Comment by seuros** [comment]
You either didnt require it in Capfile or using an older version .

**Comment by uxxman** [comment]
I am too getting this error for capistrano-sidekiq version 2.0.0.beta4

NameError: uninitialized constant Capistrano::Sidekiq

```ruby
# Capfile
require 'capistrano/sidekiq'
install_plugin Capistrano::Sidekiq
install_plugin Capistrano::Sidekiq::Systemd
```

**Comment by jcohenho** [comment]
I can't use this gem at all right now, based off of master I'm getting `uninitialized constant Capistrano::Sidekiq` as well.

**Comment by pineapplethief** [comment]
Same here, does not work with capistrano-sidekiq (1.0.3)

**Comment by AssemDeghady** [comment]
+1

**Comment by fabiode** [comment]
Had the problem right now, using `gem 'capistrano-sidekiq'`, without specifying version. Rubygems automatically downloaded 1.0.2 version. Specifying to `gem 'capistrano-sidekiq', '~> 2.0.0.beta5'` solved the problem.
