### ISSUE TITLE
LoadError: cannot load such file -- capistrano/sidekiq (2.0.0.beta4)

### ISSUE THREAD

**Issue by uxxman** [seuros/capistrano-sidekiq#251]
I am trying to setup capistrano-sidekiq but get following error on fresh install

LoadError: cannot load such file -- capistrano/sidekiq

```ruby
# Gemfile
gem 'capistrano-sidekiq', github: 'seuros/capistrano-sidekiq'

# Capfile
require 'capistrano/sidekiq'
install_plugin Capistrano::Sidekiq
install_plugin Capistrano::Sidekiq::Systemd
```

This is raised when requiring 'capistrano/sidekiq'

**Comment by seuros** [comment]
You probably running without bundle context.
`bundle exec cap .....`
This bug is not valid.

also use the rubygems version
```
gem 'capistrano-sidekiq', "~> 2.0.0.beta4"
```
