### ISSUE TITLE
systemd - in 'user' mode, sudo should not be needed

### ISSUE THREAD

**Issue by cernyjakub** [seuros/capistrano-sidekiq#254]
I try to use the master of this gem to run sidekiq in 'user' mode with systemd. I found out that the `sidekiq:install` task fails, because I don't have _sudo_ installed on my servers. I think that sudo is not needed to copy service unit file from /tmp to user's home...

https://github.com/seuros/capistrano-sidekiq/blob/6ef104f3826b13cc8f0db13f477048511d6fe96c/lib/capistrano/tasks/systemd.rake#L116

**Comment by seuros** [comment]
You right, i will fix it and release a new version

**Comment by seuros** [comment]
Let me know if it works for you.

**Comment by cernyjakub** [comment]
Perfect, works fine. Thanks!
