### ISSUE TITLE
sidekiq gem version requirement

### ISSUE THREAD

**Issue by cernyjakub** [seuros/capistrano-sidekiq#256]
Hello!

Is it necessary to require sidekiq 6 in dependences? We have an app with older Redis cluster (redis version < 4), so Sidekiq 6 does not run on it. I have forked capistrano-sidekiq and relaxed sidekiq version to `>= 5` and all works fine. I think it would help users in specific upgrade scenarios. We cannot upgrade redis cluster now, but can move to better startup mechanism using systemd...

**Comment by seuros** [comment]
you can use older version of this gem  that support sidekiq 5.

Yes it required to lock the version, because the syntax and the signals changed.

**Comment by cernyjakub** [comment]
OK, I use version 2 beta with Sidekiq 5 and the basic lifecycle works.. but undrstand your point. I will survive with my fork of this repo until I can upgrade to newer Redis cluster...
