### ISSUE TITLE
Multiple sidekiq instances?

### ISSUE THREAD

**Issue by pakerimus** [seuros/capistrano-sidekiq#257]
With Procfile I can setup multiple sidekiq instances, dividing the queues between them, by having multiple config files.
Is it possible to do it with capistrano-sidekiq?
If so, how is it configured?
And if it's not possible: do you know of an alternative?
Thank you very much!

**Comment by danielristic** [comment]
Up to version 1.0.3, this could be done using the sidekiq_processes variable. Since switching to service managers it belive this feature is unfortunately no longer supported (at least it's not documented anywhere).

**Comment by bert-mccutchen** [comment]
It looks like you can as long as you use `install_plugin Capistrano::Sidekiq::Monit`. See the following:

The Capistrano plugin loads in the rake tasks.
https://github.com/seuros/capistrano-sidekiq/blob/1e7ef1abbe26aeafe3233a12fc70ee14213eaf76/lib/capistrano/sidekiq/monit.rb#L14

Which you can see uses the `sidekiq_options` variable in the tasks.
https://github.com/seuros/capistrano-sidekiq/blob/1e7ef1abbe26aeafe3233a12fc70ee14213eaf76/lib/capistrano/tasks/monit.rake#L45-L52

Also if you're a user of `sidekiq_options_per_process`, you can see that it is still used here:
https://github.com/seuros/capistrano-sidekiq/blob/493ade199ab357ef619f8c7bb4a2bdd8bf653598/lib/generators/capistrano/sidekiq/monit/templates/sidekiq_monit.conf.erb#L5

**Comment by bert-mccutchen** [comment]
It seems that this feature has been re-added:
https://github.com/seuros/capistrano-sidekiq/commit/91f26a58175f5497259a2d8e50cc9675c38298eb

Now we just need a release, unless you're willing to point your Gemfile at master (i'm not).

**Comment by seuros** [comment]
You can use it like this : https://github.com/seuros/capistrano-example-app/blob/main/config/deploy/multi_process.rb
