### ISSUE TITLE
Systemd append StandardOutput and StandardError

### ISSUE THREAD

**Issue by farnsworth** [seuros/capistrano-sidekiq#264]
In sidekiq.service.capistrano.erb there is
<%="StandardOutput=append:#{fetch(:sidekiq_log)}" if fetch(:sidekiq_log) %>
<%="StandardError=append:#{fetch(:sidekiq_error_log)}" if fetch(:sidekiq_error_log) %>
but append is supported from version 240 of systemd (https://github.com/systemd/systemd/blob/master/NEWS) and for older versions you get an error.
Is there a way to handle older systemd versions? Should i fork?

Thank you.

**Comment by seuros** [comment]
You can place the template locally
