### ISSUE TITLE
Run sidekiq:install raise as undefined exception 

### ISSUE THREAD

**Issue by iscreen** [seuros/capistrano-sidekiq#266]
```
gem 'capistrano', '~> 3.14.1', require: false
gem 'sidekiq', '< 7'
gem 'capistrano-sidekiq', '2.0.0'
```

When I run `cap sidekiq:install` it raise exception as below

![Screen Shot 2021-01-11 at 10 28 22 AM](https://user-images.githubusercontent.com/1193025/104143331-ff4b0200-53f9-11eb-8ceb-0a71f748b7ac.png)

**Comment by seuros** [comment]
Please try latest version
