### ISSUE TITLE
Capistrano tries to reload Sidekiq, but the command is not supported

### ISSUE THREAD

**Issue by davidmles** [seuros/capistrano-sidekiq#276]
When deploying, capistrano-sidekiq triggers the `sidekiq:quiet` command with this output:

```
00:03 sidekiq:quiet
      01 sudo systemctl reload sidekiq
      01 sudo
      01 :
      01 a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
      01
    ✘ 01 myuser@1.2.3.4 0.211s
```

If I try to replicate that command directly on the server, I get this message:

```
$ sudo systemctl reload sidekiq
Failed to reload sidekiq.service: Job type reload is not applicable for unit sidekiq.service.
```

After investigating, I can't figure out why a "reload" is being called, because it's not supported by the sidekiq service (it's being called from the *systemd.rake* file, in my case).
The provided example in the repository (https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service) has a note about using **a signal** to quiet Sidekiq. **Is that what capistrano-sidekiq is trying to achieve?**

**Comment by cassiompf** [comment]
I also have the same problem

**Comment by jefvlamings** [comment]
@davidmles You're right. Mike Perman mentions this in a couple of issues as well. The reload command doesn't work as you might think it works. He proposes to use the kill command `systemctl --user kill -s TSTP sidekiq`. This will silently kill the sidekiq service without disrupting current tasks.

The sidekiq:quiet task should be rewritten to make use of this command. I've currently disabled the capistrano-sidekiq gem in my project until this is fix. This is the script that I'm currently using:

```
namespace :sidekiq do
  desc "Quiet sidekiq (stop fetching new tasks from Redis)"
  task :quiet do
    on roles(:app) do
      execute 'systemctl --user kill -s TSTP sidekiq'
    end
  end
end
```

**Comment by augustosamame** [comment]
+1

**Comment by augustosamame** [comment]
> When deploying, capistrano-sidekiq triggers the `sidekiq:quiet` command with this output:
> 
> ```
> 00:03 sidekiq:quiet
>       01 sudo systemctl reload sidekiq
>       01 sudo
>       01 :
>       01 a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
>       01
>     ✘ 01 myuser@1.2.3.4 0.211s
> ```
> 
> If I try to replicate that command directly on the server, I get this message:
> 
> ```
> $ sudo systemctl reload sidekiq
> Failed to reload sidekiq.service: Job type reload is not applicable for unit sidekiq.service.
> ```
> 
> After investigating, I can't figure out why a "reload" is being called, because it's not supported by the sidekiq service (it's being called from the _systemd.rake_ file, in my case).
> The provided example in the repository (https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service) has a note about using **a signal** to quiet Sidekiq. **Is that what capistrano-sidekiq is trying to achieve?**

The error you get during deploy is unrelated. You're deploying as sudo user:

`sudo systemctl reload sidekiq`

So the remote server is complaining that you don't have permissions to run passwordless sudo from a SSH script.

One solution is to add the following file `/etc/sudoers.d/sidekiq`

with these contents:

```
deploy ALL = NOPASSWD: /bin/systemctl start sidekiq
deploy ALL = NOPASSWD: /bin/systemctl restart sidekiq
deploy ALL = NOPASSWD: /bin/systemctl stop sidekiq
deploy ALL = NOPASSWD: /bin/systemctl status sidekiq
deploy ALL = NOPASSWD: /bin/systemctl reload sidekiq
```

**Comment by davidmles** [comment]
Yes, you are right. But in my message I also wrote the command that replicates the reload and you can see the actual error message.

After giving permission in sudoers now I have that same error message:
```
00:04 sidekiq:quiet
      01 sudo systemctl reload sidekiq
      01 Failed to reload sidekiq.service: Job type reload is not applicable for unit sidekiq.service.
    ✘ 01 stockvigilant@167.71.42.70 0.226s
```

**Comment by davidmles** [comment]
Yes, you are right. In fact I didn't give permission in sudoers because that command doesn't seem to exist. So if I give permission in sudoers I get that same error message:

```
00:04 sidekiq:quiet
      01 sudo systemctl reload sidekiq
      01 Failed to reload sidekiq.service: Job type reload is not applicable for unit sidekiq.service.
    ✘ 01 stockvigilant@167.71.42.70 0.226s
```

**Comment by seuros** [comment]
@davidmles  You probably have an outdated version of the os or systemd.

**Comment by davidmles** [comment]
> @davidmles You probably have an outdated version of the os or systemd.

It's an Ubuntu Server 20.04 LTS, with up-to-date packages.

**Comment by augustosamame** [comment]
@seuros I have the same issue as @davidmles . I also use Ubuntu 20.04 with latest updates.
My systemd version is: systemd 245 (245.4-4ubuntu3.3)

**Comment by seuros** [comment]
@augustosamame can you show me the systemd file ?

**Comment by cassiompf** [comment]
To solve the problem I just stopped using this gem and added it to my deploy.rb to restart sidekiq.service ( https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service )

```
namespace :sidekiq do
  after 'deploy:starting', 'sidekiq:stop'
  after 'deploy:finished', 'sidekiq:start'

  task :stop do
    on roles(:app) do
      within current_path do
        execute('systemctl kill -s TSTP sidekiq')
        execute('systemctl stop sidekiq')
      end
    end
  end

  task :start do
    on roles(:app) do |host|
      execute('systemctl start sidekiq')
      info "Host #{host} (#{host.roles.to_a.join(', ')}):\t#{capture(:uptime)}"
    end
  end
end
```

He stops the sidekiq using the command `systemctl stop sidekiq` and starts the sidekiq after performing all the deploy.

**Comment by augustosamame** [comment]
> @augustosamame can you show me the systemd file ?
```

[Unit]
Description=sidekiq
After=syslog.target network.target

[Service]
Type=notify
WatchdogSec=10
User=deploy
Group=deploy
UMask=0002
WorkingDirectory=/home/deploy/rails_app/current/
#ExecStart=/bin/bash -lc 'bundle exec sidekiq -C /home/deploy/rails_app/shared/config/sidekiq.yml -e production | tee ./log/sidekiq.log'
ExecStart=/bin/bash -lc 'bundle exec sidekiq -C /home/deploy/rails_app/shared/config/sidekiq.yml -e production'
Environment=MALLOC_ARENA_MAX=2

# if we crash, restart
RestartSec=1
Restart=on-failure

StandardOutput=append:/home/deploy/rails_app/shared/log/sidekiq.log
#syslog
StandardError=append:/home/deploy/rails_app/shared/log/sidekiq_error.log

# This will default to "bundler" if we don't specify it
SyslogIdentifier=sidekiq

[Install]
WantedBy=multi-user.target
```

**Comment by seuros** [comment]
I dont see a `ExecReload=/bin/kill -TSTP $MAINPID` in it.

**Comment by augustosamame** [comment]
> I dont see a `ExecReload=/bin/kill -TSTP $MAINPID` in it.

I was following the systemd example file here: https://github.com/mperham/sidekiq/blob/master/examples/systemd/sidekiq.service

And it did not include this line.
Adding this line fixed this issue.

**Comment by seuros** [comment]
@davidmles @cassiompf please see the solution above and close this issue.

**Comment by davidmles** [comment]
That seems to fix it. Thanks!
