### ISSUE TITLE
Systemd `append` mode should be documented, as it's not always available

### ISSUE THREAD

**Issue by 64kramsystem** [seuros/capistrano-sidekiq#283]
The Systemd unit used the `append` file mode (otherwise Systemd will overwrite the file by default).

However, this functionality has been added on v240, which is a relatively recent version, so it's not supported by all OSs; for example, Ubuntu Bionic (18.04.x) ships v237.

On such OSs, the result is that the log configuration is ignored:

```
Aug 13 09:55:45 my-host systemd[1]: /path/to/sidekiq.service:64: Failed to parse output specifier, ignoring: append:/path/to/sidekiq.log
Aug 13 09:55:45 my-host systemd[1]: /path/to/sidekiq.service:65: Failed to parse output specifier, ignoring: append:/path/to/sidekiq.error.log
```

I'm not sure what a clean solution to this is - this gem should probably not take the responsibility of handling the logs, however, at a minimum, this should be documented.

**Comment by saveriomiroddi** [comment]
> Can you open a PR ?

With the updated documentation? Sure. I'll also add a page in the wiki, with an example of how to handle this via Syslog-NG (just for reference).

I'll do this over the next week.
