### ISSUE TITLE
Wrong  systemctl kill command

### ISSUE THREAD

**Issue by silva96** [seuros/capistrano-sidekiq#289]
I recently updated master and now it's failing to pick up the correct sidekiq systemd service, it's adding a "1"
like this: sidekiq@1.service

```bash
sidekiq:quiet
      01 sudo systemctl kill -s TSTP sidekiq@{1..1}
      01 Failed to kill unit sidekiq@1.service: Unit sidekiq@1.service not loaded.
    ✘ 01 ubuntu@52.71.xxx.xxx 0.446s
```

Doing sudo service sidekiq restart in my machine works perfectly

This is my Capfile

```ruby
# frozen_string_literal: true

# Load DSL and set up stages
require 'capistrano/setup'

# Include default deployment tasks
require 'capistrano/deploy'
require 'capistrano/rails'
require 'capistrano/rvm'
require 'capistrano/puma'
require 'capistrano/sidekiq'
install_plugin Capistrano::Puma
install_plugin Capistrano::Puma::Systemd
install_plugin Capistrano::Sidekiq
install_plugin Capistrano::Sidekiq::Systemd

require 'capistrano/scm/git'
install_plugin Capistrano::SCM::Git

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob('lib/capistrano/tasks/*.rake').each { |r| import r }

```

This is my deploy.rb

```ruby
# frozen_string_literal: true

# config valid for current version and patch releases of Capistrano
lock '~> 3.16.0'

set :application, 'my-app' # omitted for the sake of privacy
set :repo_url, 'git@github.com:my-org/my-repo.git' # omitted for the sake of privacy 
append :linked_dirs, 'log', 'tmp/pids', 'tmp/cache', 'tmp/sockets', 'public/system', 'node_modules', 'public/packs'

set :conditionally_migrate, true
set :rails_env, 'production'
set :keep_assets, 4
set :deploy_to, '/home/ubuntu/www'
# next two lines are a hotfix for this issue https://github.com/capistrano/rails/issues/235
Rake::Task['deploy:assets:backup_manifest'].clear_actions
Rake::Task['deploy:assets:restore_manifest'].clear_actions
set :sidekiq_service_unit_name, 'sidekiq'
set :sidekiq_service_unit_user, :system
set :sidekiq_config, 'config/sidekiq.yml'
set :puma_service_unit_name, 'puma'
set :puma_systemctl_user, :system

```

This is the deploy script: (production.rb)

```ruby
# frozen_string_literal: true

ask :branch, 'master'

role(:db, %w[ubuntu@52.71.xxx.xxx]) # omitted for the sake of privacy 
role(:app, %w[ubuntu@52.71.xxx.xxx])
role(:web, %w[ubuntu@52.71.xxx.xxx])
```

Do you wonder what is happening?

**Comment by silva96** [comment]
@jclusso maybe you can help on this? I saw you authored the PR that introduced this changes.

**Comment by silva96** [comment]
I finally ran  cap production sidekiq:install again and removed all service file. This worked. (old file was not compatible)

**Comment by jclusso** [comment]
@silva96 yes, the uninstaller doesn't handle the old file type. I suppose I could make it so uninstall works on the old way and the new way so it cleans up any old service files. Additionally, I've run into issues where I had to uninstall before changing the number of processes because of the way it works. Ideally the configuration being changed would not break uninstall. Maybe I'll have some time soon to make a PR that addresses this better.

**Comment by bart3r** [comment]
> I finally ran cap production sidekiq:install again and removed all service file. This worked. (old file was not compatible)

@silva96 Can you explain in more detail 'removed all service file'.

I'm having a similar problem that I'm looking to fix.

**Comment by jclusso** [comment]
@bart3r the old structure for systemd was designed to only run one process. The new way supports mutliple processes. The file name had to be changed to end in an @ since that is how systemd multi process stuff works. Maybe we could have an upgrade task to go from the old way to the new way?
