### ISSUE TITLE
Increasing timeout option to after 'deploy:starting', 'sidekiq:stop' hook

### ISSUE THREAD

**Issue by ishields** [seuros/capistrano-sidekiq#293]
Hello, I am trying to find a way of doing this but can't find it anywhere in the documentation.  I'm trying to increase the time that sidekiq will wait for current running jobs to finish.  We have some jobs that take about 30-60 seconds to run, and though it's ok if they terminate early, I'd prefer them to not.  It would be great to increase this timeout so that the jobs finish.  Is this possible?

I'm using the default hooks

after 'deploy:starting', 'sidekiq:quiet'
after 'deploy:updated', 'sidekiq:stop'
after 'deploy:reverted', 'sidekiq:stop'
after 'deploy:published', 'sidekiq:start'

**Comment by legendetm** [comment]
The timeout can be configured in [Sidekiq configuration file](https://github.com/mperham/sidekiq/blob/46f4c6bd9ee0b2f5502a1dc0d03414989ad65063/examples/config.yml) using `:timeout` option
