### ISSUE TITLE
How do i specify how the systemd service is called?

### ISSUE THREAD

**Issue by bart3r** [seuros/capistrano-sidekiq#296]
When I deploy, I can see that the sidekiq service is called like this:
```
02:20 sidekiq:stop
      01 sudo systemctl stop sidekiq@{1..1}
      01 sudo: no tty present and no askpass program specified
```
It should **not** be adding the "@{1..1}" part at the end of the service name, because I know it can just run the following and it will work:
`sudo systemctl stop sidekiq`

How can I change the configuration for this, as I don't see any documentation about this?

**Comment by mrusa** [comment]
You can specify the systemd name with `set :sidekiq_service_unit_name, "custom_name"` in deploy.rb

**Comment by bart3r** [comment]
> You can specify the systemd name with `set :sidekiq_service_unit_name, "custom_name"` in deploy.rb

Unfortunately, this still adds the @{1..1} onto whatever we set as the sidekiq_service_unit_name

Maybe @seuros or @jclusso can provide some guidance on this?

**Comment by jclusso** [comment]
This is so it can support multiple processes. Is there a reason you want it to not run the command that way when there is just one?

**Comment by seuros** [comment]
Let a flag to disable the the multi processes support if wanted. By default we keep it on. Wdyt ?

**Comment by bart3r** [comment]
@jclusso The reason is that my system doesn't seem to support that syntax:

```
deploy@web:~$ sudo systemctl restart sidekiq@{1..1}
Failed to restart sidekiq@1.service: Unit sidekiq@1.service not found.
```


This will work though:
`deploy@web:~$ sudo systemctl restart sidekiq`

**Comment by jclusso** [comment]
@bart3r I see. Must be using an older version of systemd. @seuros I honestly think when `sidekiq_processes` is `1` it should just not include that syntax. Additionally maybe the documentation should state for multi-process support you need whatever version of systemd requires that. I don't remember off hand what that is though.

**Comment by jclusso** [comment]
@seuros just so you know I'm running `systemd 245 (245.4-4ubuntu3.15)` which supports it. I can't find when they added support for it.

**Comment by bart3r** [comment]
@seuros 

```
$ sudo systemctl --version
systemd 237
```

**Comment by bart3r** [comment]
@seuros @jclusso I like either of your suggestions above as a solution to the problem.
