### ISSUE TITLE
pidfile handling

### ISSUE THREAD

**Issue by rsluiters** [seuros/capistrano-sidekiq#44]
Sidekiq currently uses two different methods to generate the name for pidfiles: If only one Sidekiq process is running the file is only called `sidekiq.pid`, if two or more processes are running the pid files are called `sidekiq-0.pid`, `sidekiq-1.pid`, ... This leads to problems in deployment, as changing from 1 to 2 processes or back to 1 always leads to not stopped sidekiq workers.

So when e.g. changing the sidekiq_processes from 1 to 2 not the process stored in the `sidekiq.pid` is stopped but the non-existing processes `sidekiq-0/1.pid`. So the old process keeps running.

**Comment by edslocomb** [comment]
capistrano-sidekiq is currently overriding the pidfile setting in sidekiq.yml, and that is not acceptable.

**Comment by codener** [comment]
I opened a new issue on this: #156.
