### ISSUE TITLE
tty Error

### ISSUE THREAD

**Issue by benjaminsigidi** [seuros/capistrano-sidekiq#49]
After updating gem. Now getting 

```ruby
DEBUG[3842d0cf] 	sudo: no tty present and no askpass program specified
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host ***.***.365.192: sudo exit status: 1
sudo stdout: Nothing written
.
.
.

Tasks: TOP => sidekiq:monit:unmonitor
(See full trace by running task with --trace)
The deploy has failed with an error: #<SSHKit::Runner::ExecuteError: Exception while executing on host ***.***.365.192: sudo exit status: 1
sudo stdout: Nothing written
sudo stderr: sudo: no tty present and no askpass program specified
```

Not sure where the problem is

**Comment by gonzaloaune** [comment]
Im having the same error, how did you solve this ?

**Comment by benjaminsigidi** [comment]
@gonzaloaune my development rails was not the same as the production one. I just updated and the error went away and i assumed that the problem was that.

**Comment by gonzaloaune** [comment]
Solution for me was to stop using capistrano/sidekiq and start using sidekiq standalone as they mentioned in their site, I dont know why it doesnt work.

**Comment by JeskTop** [comment]
Im having the same error, I use `cap production deploy` had this problem.
but I use `cap production sidekiq:start` can work for me.

**Comment by benjaminsigidi** [comment]
@

**Comment by benjaminsigidi** [comment]
I managed to reproduce the error again. I updated my gem version to capistrano-sidekiq (0.4.0) and this brings back the error but when i lock the gem at  capistrano-sidekiq (0.3.5) i don't get any issues

**Comment by blim8183** [comment]
I rolled back to 0.3.5 and I'm not seeing the error when deploying but that seems to be because it's just not running the Monit related commands. When I try to run "cap staging sidekiq:monit:config," I get the same error.

**Comment by seuros** [comment]
set :sidekiq_monit_default_hooks, false

**Comment by dreyks** [comment]
well, this is not a solution, isn't it? i do want to use the default hooks. downgrading to 0.3.5 helped indeed

**Comment by seuros** [comment]
This is monit default hooks.

**Comment by madakopihub** [comment]
https://stackoverflow.com/questions/21659637/how-to-fix-sudo-no-tty-present-and-no-askpass-program-specified-error

`jenkins ALL=(ALL) NOPASSWD: ALL`
Put the line after all other lines in the sudoers file.
