### ISSUE TITLE
Init support?

### ISSUE THREAD

**Issue by mperham** [seuros/capistrano-sidekiq#51]
Rather than have capistrano start/stop/restart Sidekiq directly, can it integrate with upstart/systemd to control the process via init?

**Comment by rderoldan1** [comment]
+1

**Comment by hmcfletch** [comment]
We are trying to run sidekiq with capistrano-sidekiq and running into problems. The big one we are having is that the executable generated by Bundler give the incorrect location for the Gemile.

This line is incorrect:
```
ENV['BUNDLE_GEMFILE'] ||= File.expand_path("../../../releases/20150129211726/Gemfile",
  Pathname.new(__FILE__).realpath)
```
After a few releases this directory is no longer there.

**Comment by bxt** [comment]
There's a gem called [capistrano-unicorn-nginx](https://github.com/capistrano-plugins/capistrano-unicorn-nginx) which configures init.d scripts and logrotate for unicorn instances. It uses [configuration templates](https://github.com/capistrano-plugins/capistrano-unicorn-nginx/tree/master/lib/generators/capistrano/unicorn_nginx/templates) and uploads them to the server with sudo. It works pretty well and I think this gem could do something very similar for sidekiq and get some inspiration over there.

**Comment by kakra** [comment]
I'm currently using the following user instance template for systemd:

```
$ cat /etc/systemd/user/sidekiq@.service
[Unit]
Description=sidekiq for %i
After=redis.service

[Service]
Type=simple
Environment=RAILS_ENV=production
WorkingDirectory=%h/rails-apps/%i/current
ExecStart=/usr/bin/env bin/sidekiq -C config/sidekiq.yml
ExecStop=/bin/kill -TERM $MAINPID
TimeoutStartSec=300s
Restart=on-failure

[Install]
WantedBy=default.target
```

I'm still trying to figure out how to put "systemctl --user {enable|start|stop} sidekiq@myapp.service" into the capistrano deployment correctly. BTW: You need "loginctl enable-linger" on the deployment user for this to correctly apply after reboot and after logout.

**Comment by davidwessman** [comment]
@kakra Did you get this setup to work with Capistrano?
Then you configure the Timeout to be the same for Sidekiq and Capistrano?

**Comment by kakra** [comment]
I don't understand what you refer by "Timeout" but the following snippet in deploy.rb works for me:

```
# sidekiq
set :sidekiq_config, 'config/sidekiq.yml'
set :pty, false
namespace :sidekiq do
  Rake::Task['sidekiq:start'].clear_actions
  task :start do
    on roles fetch(:sidekiq_role) do |role|
      execute :systemctl, "--user start sidekiq@#{fetch :application}-#{fetch :stage}.service"
    end
  end
  Rake::Task['sidekiq:stop'].clear_actions
  task :stop do
    on roles fetch(:sidekiq_role) do |role|
      execute :systemctl, "--user stop sidekiq@#{fetch :application}-#{fetch :stage}.service"
    end
  end
end
```

Additionally, I found that putting depends like "After=redis.service" has no effect as redis is part of the system set of services while sidekiq is part of the user set of services. Cross-linking between those sets seems to be impossible. I already posted to the systemd mailing list but received no answer so far. The result is that redis may not be ready at system boot when sidekiq starts - which may work or may result in a timeout (which you referred to maybe).

I found no easy way to gracefully stop sidekiq, tho. You could try sending the right signal first at the correct step in capistrano. It wasn't important for me so I didn't bother with it too long.

**Comment by davidwessman** [comment]
Thank you for your response @kakra 
The _timeout_ I referred to is the last thing you mention, when trying to gracefully stop sidekiq.

I ended up with this:
```ruby
namespace :sidekiq do
  desc "Start sidekiq workers"
  task :start do
    on roles(:web) do
      sudo "systemctl start sidekiq-#{fetch(:rails_env)}"
    end
  end

  desc "Stop sidekiq workers"
  task :stop do
    on roles(:web) do
      sudo "systemctl stop sidekiq-#{fetch(:rails_env)}"
    end
  end

  desc "Quiet Sidekiq workers and stop accepting jobs"
  task :quiet do
    on roles(:web) do
      sudo "systemctl reload sidekiq-#{fetch(:rails_env)}"
    end
  end

  desc "Restart sidekiq workers"
  task :restart do
    stop
    start
  end
end
```
Where I configure `systemctl reload sidekiq` to send the `kill -USR1`signal.

And in my `deploy.rb`:
```ruby
before 'deploy:started', 'sidekiq:quiet'
after  'deploy:publishing', 'sidekiq:stop'
after 'deploy:published', 'passenger:restart'
after 'deploy:published', 'sidekiq:start'
```

It appears to be working ok, however I am not issuing any long running jobs at the moment.

**Comment by shaunakv1** [comment]
Without init support, capistrano-sidekiq will start the server with a bundle exec... What happens if a server restarts for maintenance.  When server comes back online, is it wrong to assume that sidekiq instance started using capistrano-sidekiq will never come back online?

**Comment by davidwessman** [comment]
@shaunakv1 That is quite what I described in my last post.

**Comment by shaunakv1** [comment]
@davidwessman agree and in-fact that is what made me ask whether or not capistrano-sidekiq supports the tasks out of box. I am assuming for the tasks you have posted one would have to install sidekiq as systemctl outside the capistrano right? and then just use capistrano to manage its life cycle? essentially not needing this gem at all?

**Comment by davidwessman** [comment]
Well, them gem is used in all the background jobs.

I created a [systemd service](https://gist.github.com/davidwessman/4f236af00981da967088d087f232b79b) like this and let the user running the rails app run these commands as sudo without a password (configurable in Debian).
