### ISSUE TITLE
monit: action failed -- Other action already in progress

### ISSUE THREAD

**Issue by sahin** [seuros/capistrano-sidekiq#59]
@seuros , I am constantly getting the following error. Any idea?

DEBUG[af8f40cf] Command: ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.1.4 /usr/bin/env sudo /usr/bin/monit monitor sidekiq_workers_vimeo_production0 )
DEBUG[9161de6c] Command: ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.1.4 /usr/bin/env sudo /usr/bin/monit monitor sidekiq_workers_vimeo_production0 )
DEBUG[25f6f1a5]         monit: action failed -- Other action already in progress -- please try again later
DEBUG[af8f40cf]         monit: action failed -- Other action already in progress -- please try again later
INFO[5b799faa] Finished in 0.098 seconds with exit status 0 (successful).
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host worker02.mll-worker.movielala.com: sudo exit status: 1

**Comment by sarkis** [comment]
I also started getting this error to a point where we needed to remove the capistrano-sidekiq gem in order to get deployments unblocked. @seuros may I ask why you need to unmonitor and monitor sidekiq during each deploy?

**Comment by ACPK** [comment]
@sarkis  - Did you ever find a solution?

**Comment by sauliusgrigaitis** [comment]
@sarkis if sidekiq is not umonitor'ed during deployment, then after deployment you may end up with two sidekiq instances - once instance started by monit and another one started by capistrano-sidekiq. 

I use workaround that works really well for me for few years now. 
```
set :sidekiq_default_hooks, false
after :restart, 'sidekiq:stop'
```
So I disable default sidekiq hooks and instead just stop sidekiq after deployment - very soon monit starts sidekiq again with new released code.

**Comment by giorgenes** [comment]
I get this error occasionally while deploying with puma. trying again usually fix the issue. seems like a race condition.

**Comment by muhammet** [comment]
Any updates ?

**Comment by jpickwell** [comment]
When calling `monit stop sidekiq` that will stop and unmonitor the service, so there's no need to do the extra `monit unmonitor sidekiq`. Also, `monit start sidekiq` will both start and monitor the service. So, I think it would be better to just do `sidekiq:stop` and `sidekiq:start`, and not use the "unmonitor" and "monitor" tasks.

I have a tangential issue with the puma plugin, where it only unmonitors and monitors, but never stops, starts, or even restarts the puma service.

References:
- [`monit start` docs](https://mmonit.com/monit/documentation/monit.html#start-name-pattern)
- [`monit stop` docs](https://mmonit.com/monit/documentation/monit.html#stop-name-pattern)
