### ISSUE TITLE
Cannot start sidekiq with jruby-1.7.18

### ISSUE THREAD

**Issue by RajRoR** [seuros/capistrano-sidekiq#65]
DEBUG[db8a581d] 	ObjectSpace is disabled; each_object will only work with Class, pass -X+O to enable
DEBUG[db8a581d] 	
DEBUG[db8a581d] 	org/jruby/RubyObjectSpace.java:173:in `each_object'
DEBUG[db8a581d] 	/data/web/api.plumlytics.com/shared/bundle/jruby/1.9/gems/sidekiq-3.3.0/lib/sidekiq/cli.rb:170:in `daemonize'
DEBUG[db8a581d] 	/data/web/api.plumlytics.com/shared/bundle/jruby/1.9/gems/sidekiq-3.3.0/lib/sidekiq/cli.rb:41:in `parse'
DEBUG[db8a581d] 	/data/web/api.plumlytics.com/shared/bundle/jruby/1.9/gems/sidekiq-3.3.0/bin/sidekiq:7:in `(root)'
DEBUG[db8a581d] 	org/jruby/RubyKernel.java:1087:in `load'
DEBUG[db8a581d] 	/data/web/api.plumlytics.com/shared/bundle/jruby/1.9/bin/sidekiq:23:in `(root)'

**Comment by seuros** [comment]
try to run sidekiq manually to locate the bug. I don't think it related to this gem.

**Comment by RajRoR** [comment]
Thanks for quick response. I tried running this manually and got the same errot:



$ bundle exec sidekiq --index 0 --environment production --config config/sidekiq.yml --daemon 

ObjectSpace is disabled; each_object will only work with Class, pass -X+O to enable
org/jruby/RubyObjectSpace.java:173:in `each_object'
/data/web/api.plumlytics.com/shared/bundle/jruby/1.9/gems/sidekiq-3.3.0/lib/sidekiq/cli.rb:170:in `daemonize'
/data/web/api.plumlytics.com/shared/bundle/jruby/1.9/gems/sidekiq-3.3.0/lib/sidekiq/cli.rb:41:in `parse'
/data/web/api.plumlytics.com/shared/bundle/jruby/1.9/gems/sidekiq-3.3.0/bin/sidekiq:7:in `(root)'
org/jruby/RubyKernel.java:1087:in `load'
/data/web/api.plumlytics.com/shared/bundle/jruby/1.9/bin/sidekiq:23:in `(root)'

**Comment by seuros** [comment]
@mperham, are you aware of this error in jruby ?

**Comment by mperham** [comment]
Is the error message not obvious?  You cannot daemonize on JRuby unless you turn on ObjectSpace.

**Comment by RajRoR** [comment]
I am running puma in daemonized mode successfully on jruby

**Comment by mperham** [comment]
Then don't daemonize Sidekiq.  Ideally you should be using Upstart to control your services, not daemonizing manually. https://github.com/mperham/sidekiq/tree/master/examples/upstart/manage-one

**Comment by RajRoR** [comment]
Thanks @mperham, currently I made it worked by setting `JRUBY_VERSION = "1.7.18"` in my `config/deploy.rb`. I'll integrate `runit` later.

**Comment by utopia2050** [comment]
Hi @mperham , @RajRoR 
I have read your discussion but I don't follow how you fixed it.
I am using jruby and I am experiencing same problem with running sidekiq as daemon with jruby.
Could you help me to solve the problem?
