### ISSUE TITLE
Custom Monit templates

### ISSUE THREAD

**Issue by ziazek** [seuros/capistrano-sidekiq#75]
Hi, 

Running ```bundle exec rails generate capistrano:sidekiq:monit:template``` resulted in
```
Could not find generator 'capistrano:sidekiq:monit:template'. Maybe you meant 'test_unit:controller' or 'test_unit:integration' or 'test_unit:generator'
Run `rails generate --help` for more options.
```

My intention is to tell Monit to restart Sidekiq if memory is exceeded. How do I use custom Monit templates? Thanks.

**Comment by ciastek** [comment]
`bundle update capistrano-sidekiq`
