### ISSUE TITLE
sidekiq_timeout overrides timeout set in config/sidekiq.yml

### ISSUE THREAD

**Issue by mattes** [seuros/capistrano-sidekiq#77]
[`stop_process`](https://github.com/seuros/capistrano-sidekiq/blob/master/lib/capistrano/tasks/capistrano2.rb#L64) just takes [`sidekiq_timeout`](https://github.com/seuros/capistrano-sidekiq/blob/master/lib/capistrano/tasks/capistrano2.rb#L18). It should look for a timeout setting in the [sidekiq.yml](https://github.com/seuros/capistrano-sidekiq/blob/master/lib/capistrano/tasks/capistrano2.rb#L10), too.

**Comment by dsawa** [comment]
+1

Setting in sidekiq.yml is ignored. 
Workaround:

```ruby
set :sidekiq_timeout, YAML.load_file(File.expand_path('../sidekiq.yml', __FILE__))[:timeout]
```
