### ISSUE TITLE
bundle exec cap production sidekiq:monit:config copies to / rather than /etc/monit/conf.d

### ISSUE THREAD

**Issue by gordonbisnor** [seuros/capistrano-sidekiq#82]
- I run  bundle exec cap production sidekiq:monit:config
- Config file is copied to /sidekiq_xxx_production.conf
- But my monit recipes are located at; /etc/monit/conf.d/sidekiq_xxx_production.conf
- Is there a configuration parameter that I am missing so set the path to monit recipes? I haven't been able to find any documentation about this. 

I am using this in combination with the Talking Quickly rails server template, capistrano recipes, and book.

**Comment by okoriko** [comment]
@gordonbisnor looking at the source it seems that `/etc/monit/conf.d` is default but anyway you can set it with `set :sidekiq_monit_conf_dir, -> { '/etc/monit/conf.d' }`
