### ISSUE TITLE
gem is always using sudo

### ISSUE THREAD

**Issue by dreyks** [seuros/capistrano-sidekiq#86]
I have a setup where running `monit` commands does not require using `sudo` for `deploy` user. However `capistrano-sidekiq` uses `sudo` regardless.
capistrano/capistrano#920 says

`If the gem is using sudo, then report it, as it shouldn't be doing, not at least without checking first.`

**Comment by seuros** [comment]
Don't report me, we can negociate.

**Comment by dreyks** [comment]
We do not negocia... oh, wait, wrong text

Let's see what capistrano suggest for such situation

**Comment by dreyks** [comment]
Ok, so I think we could take platanus/capistrano3-nginx#12 as an example

**Comment by seuros** [comment]
do you want to send a pr ?

**Comment by dreyks** [comment]
I'll try to figure something out =)

**Comment by dreyks** [comment]
seuros/capistrano-sidekiq#89
